Poordooytify/Controllers/MoodController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Poordooytify.Models;

namespace Poordooytify.Controllers
{
    public class MoodController : Controller
    {
        private PoordooytifyContext db = new PoordooytifyContext();

        // GET: Mood
        public ActionResult Index()
        {            
            return View(db.Moods.OrderByDescending(x=>x.ModifiedDate).ThenBy(o=>o.CreateDate).ToList());
        }

        public ActionResult GetTitles(string moodKey)
        {
            var songTitles = (from s in db.Songs
                              join sm in db.SongMoods on s.Key equals sm.SongKey
                              where sm.MoodKey == moodKey
                              select s.Title).Take(10).ToList();

            return Content(String.Join(", ", songTitles));
        }

        [HttpPost]
        public ActionResult AddSong(string moodKey, string songKey)
        {
            try
            {
                var sm = new SongMood() { MoodKey = moodKey, SongKey = songKey };
                db.SongMoods.Add(sm);
                var m = db.Moods.Where(x=>x.Key==moodKey).FirstOrDefault();
                m.ModifiedDate = DateTime.Now;
                db.Entry(m).State = EntityState.Modified;
                db.SaveChanges();
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }

        }

        #region Crud

        // GET: Mood/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mood mood = db.Moods.Find(id);
            if (mood == null)
            {
                return HttpNotFound();
            }
            return View(mood);
        }

        // GET: Mood/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mood/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Description,Categories,InActive,CreatedBy,CreateDate")] Mood mood)
        {
            if (ModelState.IsValid)
            {
                mood.CreateDate = DateTime.Now;
                mood.Key = PoordooytifyKey.Generate();
                db.Moods.Add(mood);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mood);
        }

        // GET: Mood/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mood mood = db.Moods.Find(id);
            if (mood == null)
            {
                return HttpNotFound();
            }
            return View(mood);
        }

        // POST: Mood/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Categories,InActive,CreatedBy,CreateDate")] Mood mood)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mood).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mood);
        }

        // GET: Mood/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mood mood = db.Moods.Find(id);
            if (mood == null)
            {
                return HttpNotFound();
            }
            return View(mood);
        }

        // POST: Mood/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Mood mood = db.Moods.Find(id);
            db.Moods.Remove(mood);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #endregion
    }
}

Poordooytify/Controllers/SonglibController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Poordooytify.Models;
using Dropbox.Api;
using System.Threading.Tasks;
using System.Data.Entity;
using System.Globalization;
using E.Deezer;

namespace Poordooytify.Controllers
{
    public class SonglibController : Controller
    {
        // GET: Songlib
        PoordooytifyContext db = new PoordooytifyContext();
       
        public ActionResult Index(string q = "", string r = "", string m = "", int pageSize = 20, int page = 1 )
        {

            var dbSongs = db.Songs.Where(x => x.CloudToken.Inactive == false);
            var pagedSongs = dbSongs.OrderByDescending(o => o.Id).Skip((page - 1) * pageSize).Take(pageSize);
            var songs = new List<Song>();
            ViewBag.Moods = db.Moods.OrderByDescending(x => x.ModifiedDate).ThenBy(o => o.CreateDate).ToList();
            var Loadbutton = false;
            var ImHome = false;

            if (page>1)
            {
                var SongIds = Newtonsoft.Json.JsonConvert.SerializeObject(pagedSongs.Select(s => s.Id));
                @ViewBag.SongIds = SongIds;
                return PartialView("_SongCard", pagedSongs);
            }

            if (string.IsNullOrEmpty(m))
            {
                if (string.IsNullOrEmpty(q))
                {
                    if (string.IsNullOrEmpty(r))
                    {
                        songs = pagedSongs.ToList();
                        ImHome = true;
                    }
                    else
                        songs = dbSongs.OrderByDescending(d => d.PlayCount).Take(20).ToList();
                    Loadbutton = true;
                }
                else
                {
                    songs = dbSongs.Where(x => x.Title.Contains(q) || x.Artist.Contains(q) || x.Genre.Contains(q)).Take(20).OrderBy(o => o.PlayCount).ToList();
                }
            }
            else
            {
                songs = (from s in dbSongs
                              join sm in db.SongMoods on s.Key equals sm.SongKey
                              where sm.MoodKey == m && s.CloudToken.Inactive == false
                              select new 
                              {
                                  Id = s.Id,
                                  Title = s.Title,
                                  Artist = s.Artist,
                                  Link = s.Link
                              }).ToList().Select(s => new Song
                                 {
                                     Id = s.Id,
                                     Title = s.Title,
                                     Artist = s.Artist,
                                     Link = s.Link
                                 }).ToList();
                TempData["InstantPlaySongId"] = songs.FirstOrDefault().Id;
            }

            ViewBag.Home = ImHome;
            ViewBag.Loadbutton = Loadbutton;
            return View(songs);
        }

        public ActionResult Create()
        {
            var storage = db.CloudTokens.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.AccountName }).ToList();
            ViewBag.storage = storage;
            ViewBag.genres = Newtonsoft.Json.JsonConvert.SerializeObject(db.Genres.Select(g => g.Name).ToList());
            return View();
        }

        [HttpPost]
        public ActionResult GetLink(int songId)
        {
            var song = new Song();
            string songLink = string.Empty;
            try
            {
                song = db.Songs.Find(songId);
                songLink = song.Link;
                db.Entry(song).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch { }
            return Json(new { songLink = songLink }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public EmptyResult AddPlayCount(int songId)
        {
            var song = new Song();
            try
            {
                song = db.Songs.Find(songId);
                song.PlayCount = song.PlayCount + 1;
                db.Entry(song).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch { }
            //return Json( song.PlayCount, JsonRequestBehavior.AllowGet);
            return null;
        }

        public async Task<ActionResult> Artists(string q)
        {
            //Create a new DeezerSession for your application
            //You'll retrieve a 'Deezer' object which you can browse the API from.
            var Deezer = DeezerSession.CreateNew();

            //This performs an async search on Deezer for albums matching "Abba"
            //Mapping to API: search/album?q=Abba&index=0&limit=25
            //var search = await Deezer.Search.Albums("Abba");

            //You can vary the size and starting position of querys...

            //Will only return UP-TO a maximum of 10 artists matching "Queen"
            //Mapping to API: search/artist?q=Queen&index=0&limit=10
            var small_search = await Deezer.Search.Artists(q, 10);

            //This will return for UP-TO a maximum of 15 tracks by Elvis. 
            //These will be offset by 20 places in the results. This is useful for pagination.
            //Mapping to API: search/track/?q=Elivs&index=20&limt=15
            //var offset_search = await Deezer.Search.Tracks("Elivs", 20, 15);

            var artists = small_search.Select(x => x.Name).ToList();
            return Json(artists, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadAudioFile(HttpPostedFileBase audioFile, Song song, string BitRate)
        {
            TempData["InstantPlaySongId"] = 0;
            var songId = 0;
            try
            {
                if (audioFile.ContentLength > 0)
                {
                    //song.Key = PoordooytifyKey.Generate();
                    TextInfo textInfo = new CultureInfo("en-US", false).TextInfo;
                    song.Title = textInfo.ToTitleCase(song.Title);
                    song.Artist = textInfo.ToTitleCase(song.Artist);
                    song.PlayCount = 0;
                    db.Songs.Add(song);
                    song.OrigFilename = Path.GetFileName(audioFile.FileName);
                    song.DateAdded = DateTime.Now;
                    song.Key = PoordooytifyKey.Generate();
                    db.SaveChanges();

                    songId = song.Id;
                    string _FileName = song.Title + " - " + song.Artist + " [" + song.Id + "]" + Path.GetExtension(audioFile.FileName);
                    string _path = Path.Combine(Server.MapPath("~/TempUpload"), _FileName);
                    audioFile.SaveAs(_path);
                    var fileToUpload = ConvertToOpus(_path, BitRate);
                    if (System.IO.File.Exists(_path))
                    {
                        System.IO.File.Delete(_path);
                    }
                    var task = Task.Run(() => UploadToDropbox(fileToUpload, song.Id, song.CloudTokenId));
                    task.Wait();
                    TempData["InstantPlaySongId"] = song.Id;
                    TempData.Keep("InstantPlaySongId");
                }
            }
            catch(Exception ex)
            {
                TempData["Message"] = "File upload failed. Err: " + ex.Message;
                db.Entry(song).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            finally { }

            return RedirectToAction("Index");
        }

        private string ConvertToOpus(string inputFile, string BitRate)
        {
            string outputFile = Path.Combine(Server.MapPath("~/TempUpload"), Path.GetFileNameWithoutExtension(inputFile) + ".opus");
            var ffMpeg = new NReco.VideoConverter.FFMpegConverter();

            ffMpeg.ConvertMedia(inputFile,
                null, // autodetect by input file extension 
                outputFile,
                null, // autodetect by output file extension 
                new NReco.VideoConverter.ConvertSettings()
                {
                    CustomOutputArgs = " -acodec libopus -b:a " + BitRate + " -vbr on -compression_level 10 "
                }
            );

            return outputFile;
        }

        private async Task UploadToDropbox(string localPath, int songId, int CloudTokenId)
        {
            var token = db.CloudTokens.Find(CloudTokenId).Token;
            var song = db.Songs.Find(songId);
            using (var dbx = new DropboxClient(token))
            {
                var remotePath = "/" + Path.GetFileName(localPath);
                using (var fileStream = System.IO.File.Open(localPath, FileMode.Open))
                {
                    var s = await dbx.Files.UploadAsync(remotePath, body: fileStream);
                    var result = await dbx.Sharing.CreateSharedLinkWithSettingsAsync(remotePath);
                    song.Link = result.Url;
                    db.Entry(song).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
            if (System.IO.File.Exists(localPath))
            {
                System.IO.File.Delete(localPath);
            }
        }

    }
}

Poordooytify/Views/Songlib/Create.cshtml
@model Poordooytify.Models.Song

@{
    ViewBag.Title = "Music Uploader";
}

@section styles {    
<link href="@Url.Content("~/Content/typeaheadjs.css")" rel="stylesheet" />
    @*<link href="@Url.Content("~/Content/tagsinput.css")" rel="stylesheet" />*@
    <style>
        .bootstrap-tagsinput {
            background-color: #fff;
            border: 1px solid #ccc;
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
            display: block;
            padding: 4px 6px;
            color: #555;
            vertical-align: middle;
            border-radius: 4px;
            max-width: 100%;
            line-height: 22px;
            cursor: text;
        }

            .bootstrap-tagsinput input {
                border: none;
                box-shadow: none;
                outline: none;
                background-color: transparent;
                padding: 0 6px;
                margin: 0;
                width: auto;
                max-width: inherit;
            }
    </style>
}

<div class="col-md-12">
    <h2>Upload your song</h2>
</div>

<div id="uploadTip" style="display:none" class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>[Upload Issue]</strong> Please use Chrome browser as you might encounter trouble uploading files in Firefox for Android.
</div>

<div class="row">
    <div class="col-md-6">

        <form action="@Url.Action("UploadAudioFile", "songlib")" method="post" enctype="multipart/form-data" name="Uploading" id="form-submit" >
            @Html.AntiForgeryToken()

            <div class="form-group">
                <label for="audioFile" class="control-label col-md-3">File</label>
                <div class="col-md-9">
                    <input type="file" name="audioFile" id="audioFile" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label" for="BitRate">Bitrate</label>
                <div class="col-md-9">
                    <select name="BitRate" id="BitRate" class="form-control">
                        <option value="48000">48Kbps Stereo</option>
                        <option value="24000">24Kbps Mono</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="@nameof(Model.Title)" class="control-label col-md-3">@nameof(Model.Title)</label>
                <div class="col-md-9">
                    <input type="text" class="form-control" name="@nameof(Model.Title)" id="@nameof(Model.Title)" />
                </div>
            </div>

            <div class="form-group">
                <label for="@nameof(Model.Artist)" class="control-label col-md-3">@nameof(Model.Artist)</label>
                <div class="col-md-9">
                    <input type="text" class="form-control typeahead" name="@nameof(Model.Artist)" id="@nameof(Model.Artist)" autocomplete="off" />
                </div>
            </div>

            <div class="form-group">
                <label for="@nameof(Model.Genre)" class="control-label col-md-3">@nameof(Model.Genre)</label>
                <div class="col-md-9">
                    <input type="text" data-role="tagsinput" class="form-control" name="@nameof(Model.Genre)" id="@nameof(Model.Genre)" placeholder="Tap to add more" />
                </div>
            </div>

            <div class="form-group">
                <label for="@nameof(Model.CloudTokenId)" class="control-label col-md-3">Cloud Account</label>
                <div class="col-md-9">
                    @Html.DropDownListFor(m => m.CloudTokenId, ViewBag.storage as List<SelectListItem>, new { @class = "form-control" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-9">
                    <button type="submit" class="btn btn-outline-primary">Upload</button>
                    <a href="@Url.Action("Index", "Songlib")" class="btn btn-secondary float-right" role="button" aria-pressed="true"><span class="glyphicons glyphicons-arrow-left"></span> Song List</a>
                </div>
            </div>
        </form>



    </div>

</div>



@section Scripts {
@{ Html.RenderPartial("_ValidationScriptsPartial"); }


    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.min.js" integrity="sha256-LOnFraxKlOhESwdU/dX+K0GArwymUDups0czPWLEg4E=" crossorigin="anonymous"></script>    
    <script>
        $(document).ready(function () {
            $('.typeahead').typeahead({
                autoSelect: true,
                minLength: 3,
                delay: 200,
                source: function (query, process) {
                    $.ajax({
                        url: '@Url.Action("Artists","Songlib")',
                        data: { q: query },
                        dataType: 'json'
                    })
                        .done(function (response) {
                            return process(response);
                        });
                }
            });
        });
    </script>

    <script src="@Url.Content("~/Scripts/tagsinput.js")"></script>
    <script>
        $('#Genre').tagsinput({
            typeahead: {
                source: @Html.Raw(ViewBag.genres),
                maxTags: 3        
            }
        });
        $('#Genre').on('itemAdded', function (event) {
            $('.bootstrap-tagsinput').find('input').css("color", "transparent");;
        });

    </script>

    <script>
        var isWebkit = true;
        var isMobile = true;
        $(document).ready(function () {
            isWebkit = 'WebkitAppearance' in document.documentElement.style
            isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);

            if (!isWebkit) {
                $('#uploadTip').show();
                if (!isMobile) {
                    $('#uploadTip').hide();
                }
            }

        });
    </script>

@{ Html.RenderPartial("_SubmitAnimationScriptPartial"); }

}

Poordooytify/Views/Songlib/_SongCard.cshtml
@model IEnumerable<Poordooytify.Models.Song>

@helper Moods(string SongKey)
{
foreach (var m in ViewBag.Moods as List<Poordooytify.Models.Mood>)
{
        <a class="dropdown-item mood-link" href="@Url.Action("AddSong", "Mood", new { moodKey = m.Key, songKey = SongKey })">@m.Name</a>
}
}

@if (Model.Count() > 0)
{
    <div class="card">
        @foreach (var song in Model)
        {
            if (!string.IsNullOrEmpty(song.Link))
            {
                song.Link = song.Link.Remove(song.Link.Length - 1, 1) + "1";
            }
            <div class="card-header" role="tab" id="heading-@song.Id">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse-@song.Id" aria-expanded="true" aria-controls="collapse-@song.Id">
                    @song.Title <small class="text-muted">@song.Artist</small>
                </a>
            </div>
            <div id="collapse-@song.Id" data-songId="@song.Id" data-titleartist="@(song.Title + " by " + song.Artist)" class="collapse " role="tabpanel" aria-labelledby="heading-@song.Id">
                <div class="card-block">
                </div>
                <div class="card-footer card-outline-success">
                    <!-- Example single danger button -->
                    <div class="btn-group">
                        <button type="button" class="btn btn-outline-success btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="@Url.Content("~/Images/star.png")" />
                        </button>
                        <div class="dropdown-menu">
                            @Moods(song.Key)
                            <a class="dropdown-item" href="#">More...</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("create","mood")">Create Mood</a>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>

    <input type="hidden" id="arrAjaxSongIds" value="@ViewBag.SongIds" />
}
else
{
    <i>LAsT_PAgE_0000</i>
}